---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 8080, host: 80}]
  - ["forwarded_port", {guest: 8080, host: 9090}]

provisioner:
  name: chef_solo

platforms:
  - name: 'jcalonsoh/chef-centos-6.6'

suites:
  - name: default
    run_list:
      - recipe[yum-epel::default]
      - recipe[java::default]
      - recipe[jenkins-server::master]
      - recipe[jenkins-server::nginx]
    attributes:
      jenkins-server:
        nginx:
          install: true
          server_default: true
      jenkins:
        master:
          listen_address: '0.0.0.0'
          install_method: 'package'
      java:
        install_flavor: 'oracle'
        jdk_version: '7'
        oracle:
          accept_oracle_download_terms: true
      yum:
        epel:
          enabled: true
      nginx:
        default_site_enabled: false
